package Request;

public enum RequestCode {
	GENERATE_UNIFORM_DATA,
	NEW_DATA,
	GENERATE_GAUSSIAN_DATA,
	GENERATE_POISSON_DATA,
	SHOW_DATA,
	UPDATE_SEED,
	UPDATE_AMOUNT,
	CALC_MIN_DIS,
	CALC_MAX_DIS,
	CALC_STATS, GET_DATA, SEND_DATA,
	RESULT_MIN_DIS,
	RESULT_MAX_DIS,
	NEW_PAIR_DATA_MAX,
	NEW_PAIR_DATA_MIN,
}
